[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Mental Health: Investigating the Applications and Impacts of Intelligent Technologies in Diagnosing and Treating Mental Illness"
